### PR TITLE
Upgrade Megahit, python, and clean up code

### PR DESCRIPTION
**Pull request by jayrbolton**
- Upgrade to the python 3 kbase/sdkbase2:python image
- Upgrade Megahit to 1.2.8 and fetch from git release archive
- Remove non-active KBase staff from kbase.yml authors
- Add to release notes
- Move installed clients into src/installed_clients
- Remove various unused files
- Add dependencies.json
- Add megahit threadlimit of (num_cores-1) (see PR #21)

@bio-boris I included your update in PR #21 in this one

Tests pass :heavy_check_mark:

### CODE REVIEW

**Comment by bio-boris** [comment]
Looks good enough to merge and test on CI. Can we get a develop branch on here from and merge into that?

**Comment by jayrbolton** [comment]
Good call, will do.
I may also add a couple more test cases this morning.

**Comment by psdehal** [comment]
Are you going to make a new branch?

**Comment by bio-boris** [comment]
@psdehal Yes we would like to merge this into a develop branch but we don't have access.

**Pull request merged**
