### PR TITLE
updated citation and patch

### PR DESCRIPTION
**Pull request by mclark58**
Updated the citation format to PLOS and increased the patch number by 1

### CODE REVIEW

**Comment by dcchivian** [comment]
@mclark58 please describe what you changed in RELEASE_NOTES.md

**Comment by mclark58** [comment]
updated!

**Comment by dcchivian** [comment]
@sychan @scanon @psdehal I don't have merge permission on this repo

**Comment by mclark58** [comment]
@sychan, should be good to go! :)

**Pull request merged**
